# Generated by Django 3.0.5 on 2020-04-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_auto_20200403_1507'),
        ('documentos', '0002_documeto_pertence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documeto',
            name='pertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='colaborador.Colaborador'),
            preserve_default=False,
        ),
    ]
